import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { IoMdHome } from "react-icons/io";
import { GoTerminal } from "react-icons/go";
import { FaUser } from "react-icons/fa";

import { Button } from "@/components/ui/button";
import { ModeToggle } from "@/components/ModeToggle";
import { FloatingDock } from "@/components/ui/FloatingDock";
import { currentUser } from "@clerk/nextjs/server";
import { syncUser } from "@/actions/user.action";
import SideBar from "@/components/SideBar";
import {Toaster} from "react-hot-toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const user = await currentUser();

 if(user) await syncUser();



  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Top bar with Sign In/Sign Up & ModeToggle */}
          <div className="flex justify-end items-center p-4 gap-4">
            <ModeToggle />
            <SignedOut>
              <SignInButton mode="modal">
                <Button className="text-lg px-4 py-2">Sign In</Button>
              </SignInButton>
              <SignUpButton mode="modal">
                <Button variant="outline" className="text-lg px-4 py-2">Sign Up</Button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </div>

          {/* FloatingDock (Fixed Center) */}
          <div className="fixed top-16 left-1/2 transform -translate-x-1/2 z-50">
            <FloatingDock
              className="flex gap-x-8 p-4"
              items={[
                { title: "Home", icon: <IoMdHome />, href: "/" },
                ...(user
                  ? [
                      { title: "Product", icon: <GoTerminal />, href: "/notifications" },
                      { title: "About", icon: <FaUser />, href: "/profile" },
                    ]
                  : []),
              ]}
            />
          </div>

          {/* Main Layout with Sidebar (3:9 Ratio) */}
          <div className="pt-28">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <div className="min-h-screen">
                <main className="py-8">
                  <div className="max-w-7xl mx-auto px-4">
                    <div className="grid grid-cols-12 gap-6">
                      {/* Sidebar (3/12 - 25%) */}
                      <div className="hidden lg:block lg:col-span-3 p-4">
                        <SideBar/>
                      </div>

                      {/* Main Content (9/12 - 75%) */}
                      <div className="lg:col-span-9">{children}</div>
                    </div>
                  </div>
                </main>
              </div>
              <Toaster/>
            </ThemeProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
